config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :users
  resources :projects

  get '/register', to: "registrations#new", as: 'new_register'
  post '/register', to: "registrations#create", as: 'register'

  get '/login', to: "sessions#new", as: 'new_login'
  post '/login', to: "sessions#create", as: 'login'
  delete '/logout', to: "sessions#destroy", as: 'logout'

end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :project

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

	validates :username, presence: true
	validates :email, presence: true, uniqueness: true, 
		format: {with: /\A[^@\s]+@([^@\s]+\.)+[^@\W]+\z/ }
  has_many :projects  

	before_save { self.email = email.downcase }
	has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@projects = Project.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :user_logged_in, only: [:create,:edit,:destroy]

  # show all projects by everyone 
  def index
    @projects = Project.all
  end

  # show all projects according to params[:id]
  def show 
    @project = Project.find_by(id: params[:id])
  end

  # create new project
  def new 
    @user = User.find_by(id: params[:id])
    @project = @user.projects.build
  end

  def create 
    user = User.find(params[:user_id])
    @project = user.projects.create(project_params)

    if @project.save
      flash[:success] = "New job / project listing created!"
      redirect_to root_url
    else
      render 'projects#new'
    end
  end

  # make changes to existing project
  def edit 
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      redirect_to current_user
    else
      render 'projects#edit'
    end
  end

  # delete project
  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy
    redirect_to current_user
  end

  private
    # check for the permitted input for security
    def project_params
      params.require(:project)
        .permit(:title, :description)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login @user
      flash[:notice] = "You have succesfully registered your account"
      redirect_to @user
    else
      render :new
    end
  end


  private
  # check for the permitted input for security
    def user_params
      params.require(:user)
        .permit(:username, :email, :password, :password_confirmation)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      login user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to root_path
    else
      flash[:error] = "Invalid email / password combination"
      redirect_to new_login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(id: params[:id])
    @current_user = current_user
    @projects = @user.projects
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title="")
		base_title = "TalentCrewDB"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

  def login(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def user_logged_in?
    !current_user.nil?
  end

   def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/views/home/index.html.erb
<div class="container">

  <h4>Showbiz Jobs / Projects + Talent Directory.</h4>
  <p>This is a test homepage.</p>

  <%= render 'projects/index' %>

</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
    <nav>
      <div class="container fluid">
    <%= link_to image_tag("tcdb_logo.png", :height => "50", :alt=> "TalentCrewDB"), root_path %>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_logged_in? %>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>

        <% else %>
          <li><%= link_to "Register", register_path %></li>
          <li><%= link_to "Login", new_login_path %></li>
        <% end %>
      </ul>

  </div>
      </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <div>
      <% flash.each do |k, v| %>
        <p><%= "#{k}: #{v}" %></p>
      <% end %>
    </div>

  <%= yield %>

	</div>

</body>
</html>

app/views/listings/edit.html.erb
<div class = "row">
  <div class = "col-md-4 col-md-offset-4">
    <h1><center> Edit your listing </center></h1>
    <%= form_for([current_user, @listing] do |f| %>
      
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    <br>
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
    <br>
      <%= f.submit "Submit", class: "btn btn-primary btn-block" %>

    <% end %>
  </div>
</div>

app/views/listings/new.html.erb
<div class = "row">
  <div class = "col-md-4 col-md-offset-4">
    <h1><center> Create new listing </center></h1>
    <%= form_for([@user, @listing], url: new_listing_path) do |f| %>
      
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    <br>
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
    <br>
      <%= f.submit "Submit New Listing", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

app/views/projects/_index.html.erb
<% @projects.each do |project| %>
  <h1><%= project.title %></h1>
  <%= link_to "Job / Project Listing", project_path %>
<% end %>

app/views/projects/_project.html.erb
<li id="projects-<%= project.id %>">
  <span class="content"><%= project.title %></span>
  <span class="edit content">
  <% if current_user?(project.user) %>
    <%= link_to "edit", edit_user_project_path(project.user,project) %> 
    <%= link_to "delete", [project.user,project], method: :delete, data: {confirm: "Confirm deletion?"} %>
  <% end %>
  </span>
</li>

app/views/projects/edit.html.erb
<div class = "row">
  <div class = "col-md-4 col-md-offset-4">
    <h1><center> Edit your project </center></h1>
    <%= form_for([current_user, @project] do |f| %>
      
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    <br>
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
    <br>
      <%= f.submit "Submit", class: "btn btn-primary btn-block" %>

    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class = "row">
  <div class = "col-md-4 col-md-offset-4">
    <h1><center> Create new project </center></h1>
    <%= form_for([@user, @project], url: new_project_path) do |f| %>
      
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    <br>
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
    <br>
      <%= f.submit "Submit New Project", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<%= provide(:title, "Project") %>

<div class = "center">
  <h2><%= @project.title %></h2>
</div>
<h2><%= @project.description %></h2>
<h2>Owned By : <%= @project.user.name %></h2>
<p># PLACE BOOKING FORM HERE</p>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.username %></h1>
      <p><%= @user.email %></p>
      	<br><hr>
      <h2>Your Projects</h2>
      <div><%= render 'projects/project' %></div>
    </section>

    <div class = "col-md-4">
    	<%= link_to "Submit New Project", new_user_project_path(@user) %>
    </div>
  </aside>
</div>